#!/usr/bin/env ruby
# frozen_string_literal: true

# stdlib
require 'optparse'

# third party
require 'toml-rb'

# TODO
class Parser
  HASH_COMMENT_EXTENSIONS = %w[.tf .toml .yaml .yml].freeze
  PLACEHOLDER_RE = /(\[\[\s*(.*?)\s*\]\])/i
  TEMPLATE_EXTENSION = '.jtpl'

  attr_reader :ssot

  def initialize(ssot)
    ssot = Pathname.new(ssot)
    raise ArgumentError, "SSoT file '#{ssot}' does not exist." unless ssot.file?

    @ssot = TomlRB.load_file(ssot)
  end

  def process(target)
    target = Pathname.new(target)

    if target.file?
      render target
    elsif target.directory?
      templates = target.glob("*#{TEMPLATE_EXTENSION}")
      templates.each { |template| render template }
    else
      raise ArgumentError, "'#{target}' neither a file nor a directory."
    end
  end

  def clean(target)
    directory = Pathname.new(target)
    raise ArgumentError, "'#{directory}' is not a directory." unless directory.directory?

    directory.glob("**/*#{TEMPLATE_EXTENSION}").each do |template|
      rendered = template.sub_ext('')
      rendered.unlink if rendered.file?
    end
  end

  private

  def sub_placeholders(template)
    text = template.read

    text.gsub(PLACEHOLDER_RE) do
      placeholder = ::Regexp.last_match(1)
      key = ::Regexp.last_match(2)

      sub_keys = key.split('.')
      value = @ssot.dig(*sub_keys)

      value ? value.to_s : placeholder
    end
  end

  def render(template)
    rendered = Pathname.new(template.sub_ext(''))
    rendered.write(sub_placeholders(template))
    return unless HASH_COMMENT_EXTENSIONS.include?(rendered.extname)

    rendered.write("# File generated by ssot on #{Time.now.utc}.\n\n#{rendered.read}")
  end
end

if $PROGRAM_NAME == __FILE__
  banner = 'usage: ssot [options] [target...]'
  options = {}

  OptionParser.new do |opts|
    opts.banner = banner

    opts.on('-s', '--ssot FILE', 'Set source of truth') do |f|
      options[:ssot] = f
    end
    opts.on('-c', '--clean', 'Remove rendered templates in target') do |c|
      options[:clean] = c
    end
    opts.on('-h', '--help', 'Prints this help') do
      puts opts
      exit
    end
  end.parse!

  target = ARGV

  if target.empty?
    puts banner
    exit 1
  end

  parser = Parser.new(options[:ssot])

  if options.include?(:clean)
    target.each { |target| parser.clean target }
  else
    target.each { |target| parser.process target }
  end
end
