#!/usr/bin/env ruby
# frozen_string_literal: true

require 'optparse'
require 'toml-rb'

# TODO
class Parser
  HASH_COMMENT_EXTENSIONS = %w[.tf .toml .yaml .yml].freeze
  PLACEHOLDER_RE = /(\[\[\s*(.*?)\s*\]\])/i
  TEMPLATE_EXTENSION = '.jtpl'

  def self.clean(target)
    directory = Pathname.new(target)
    raise ArgumentError, "'#{directory}' is not a directory." unless directory.directory?

    directory.glob("**/*#{TEMPLATE_EXTENSION}").each do |template|
      rendered = template.sub_ext('')
      rendered.unlink if rendered.file?
    end
  end

  attr_reader :ssot

  def initialize(path)
    file = Pathname.new(path)
    raise ArgumentError, "SSoT file '#{path}' does not exist." unless file.file?

    @ssot = TomlRB.load_file(file)
  end

  def process(target)
    target = Pathname.new(target)

    if target.file? && target.extname == TEMPLATE_EXTENSION
      raise ArgumentError, "'#{target}' is not a #{TEMPLATE_EXTENSION} file." unless target.extname == TEMPLATE_EXTENSION

      render target
    elsif target.directory?
      templates = target.glob("**/*#{TEMPLATE_EXTENSION}")
      templates.each { |template| render template }
    end
  end

  private

  def sub_placeholders(text)
    text.gsub(PLACEHOLDER_RE) do
      placeholder = ::Regexp.last_match(1)
      key = ::Regexp.last_match(2)

      sub_keys = key.split('.')
      value = @ssot.dig(*sub_keys)
      value.nil? ? placeholder : value.to_s
    end
  end

  def render(template)
    text = sub_placeholders(template.read)
    rendered = template.sub_ext('')
    if HASH_COMMENT_EXTENSIONS.include?(rendered.extname)
      text = "# File generated by ssot on #{Time.now.utc}.\n\n#{text}"
    end
    rendered.write(text)
  end
end

if $PROGRAM_NAME == __FILE__
  banner = 'usage: ssot [options] [target...]'
  options = {}

  OptionParser.new do |opts|
    opts.banner = banner

    opts.on('-s', '--ssot FILE', 'Set source of truth') do |f|
      options[:ssot] = f
    end
    opts.on('-c', '--clean', 'Remove rendered templates in target') do |c|
      options[:clean] = c
    end
    opts.on('-h', '--help', 'Prints this help') do
      puts opts
      exit
    end
  end.parse!

  targets = ARGV

  if targets.empty?
    puts banner
    exit 1
  end

  if options.include?(:clean)
    targets.each { |target| Parser.clean(target) }
  else
    if options[:ssot].nil?
      puts banner
      exit 1
    end

    parser = Parser.new(options[:ssot])
    targets.each { |target| parser.process(target) }
  end
end
