# frozen_string_literal: true

require_relative "ssot/version"

require "pathname"

require "toml"

module Ssot
  class Error < StandardError; end

  class Parser
    HASH_COMMENT_EXTENSIONS = %w[.tf .toml .yaml .yml].freeze
    PLACEHOLDER_RE = /(\[\[\s*(.*?)\s*\]\])/i
    TEMPLATE_EXTENSION = ".jtpl"

    attr_reader :ssot

    def initialize(ssot_path)
      ssot_path = Pathname ssot_path
      raise ArgumentError, "SSoT file '#{ssot_path}' does not exist." unless ssot_path.file?

      @ssot = TOML::Parser.new(ssot_path.read).parsed
    end

    def process(target)
      # decide flow based on target path type
      if target.file?
        process_template target
      elsif target.directory?
        process_directory target
      else
        raise ArgumentError, "Target '#{target}' neither a file nor a directory."
      end
    end

    private

    def process_directory(directory)
      # get all templates in target directory
      templates = directory.glob("*#{TEMPLATE_EXTENSION}")
      # iterate over each one and substitute the placeholders
      templates.each { |template| process_template template }
    end

    def process_template(template)
      text = template.read

      rendered = text.gsub(PLACEHOLDER_RE) do
        placeholder = ::Regexp.last_match(1)
        key = ::Regexp.last_match(2)

        sub_keys = key.split(".")
        value = ssot.dig(*sub_keys)

        value ? value.to_s : placeholder
      end

      # strip TEMPLATE_EXTENSION
      processed = template.sub_ext("")

      if HASH_COMMENT_EXTENSIONS.include? processed.extname
        rendered = "# File generated by ssot on #{Time.now.utc}.\n\n" + rendered
      end

      processed.write(rendered)
      puts "#{template} -> #{processed}"
      processed
    end
  end
end
