#!/usr/bin/env ruby
# frozen_string_literal: true

require "ssot"

if ARGV.size != 2
  puts "USAGE: ruby lib/ssot.rb ssot.toml target"
  exit 1
end

ssot, target = ARGV
# Cast args to pathnames
ssot = Pathname ssot
target = Pathname target

parser = Ssot::Parser.new(ssot)
parser.process(target)
